"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Manually modified:  No
"""

# Import individual modules to register their metadata:

from . import MD_sentinel_2_l2a  # noqa: F401
