"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         3dep-lidar-dtm
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = '3dep-lidar-dtm'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='data',
            longname='COG data',
            description=None,
            unit='metre',
            roles=['data'],
            dtype='float32',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        )
    ]
)

register_static_metadata(provider, collection, metadata)
