"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         alos-fnf-mosaic
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'alos-fnf-mosaic'

metadata = CollectionMetadata(
    Variable(
        name='C',
        longname='C',
        description='Forest vs Non-Forest classification',
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=0,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    )
)

register_static_metadata(provider, collection, metadata)
