"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         alos-palsar-mosaic
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'alos-palsar-mosaic'

metadata = CollectionMetadata(
    Variable(
        name='HH',
        longname='HH',
        description='HH polarization backscattering coefficient, 16-bit DN.',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='HV',
        longname='HV',
        description='HV polarization backscattering coefficient, 16-bit DN.',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='VH',
        longname='VH',
        description='VH polarization backscattering coefficient, 16-bit DN (high-sensitive beam quad-mode only).',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='VV',
        longname='VV',
        description='VV polarization backscattering coefficient, 16-bit DN (high-sensitive beam quad-mode only).',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
