"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         chloris-biomass
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'chloris-biomass'

metadata = CollectionMetadata(
    Variable(
        name='biomass',
        longname='Annual estimates of aboveground woody biomass.',
        description=None,
        unit='tonnes',
        roles=['data'],
        dtype='uint32',
        preferred_resampling=None,
        nodata_value=2147483647,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='biomass_wm',
        longname='Annual estimates of aboveground woody biomass (Web Mercator).',
        description=None,
        unit='tonnes',
        roles=['data'],
        dtype='uint32',
        preferred_resampling=None,
        nodata_value=2147483647,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='biomass_change',
        longname='Annual estimates of changes (gains and losses) in aboveground woody biomass from the previous year.',
        description=None,
        unit='tonnes',
        roles=['data'],
        dtype='int16',
        preferred_resampling=None,
        nodata_value=-32768,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='biomass_change_wm',
        longname='Annual estimates of changes (gains and losses) in aboveground woody biomass from the previous year '
        '(Web Mercator).',
        description=None,
        unit='tonnes',
        roles=['data'],
        dtype='int16',
        preferred_resampling=None,
        nodata_value=-32768,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
