"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         chesapeake-lu
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'chesapeake-lu'

metadata = CollectionMetadata(
    Variable(
        name='data',
        longname='Land Use Classes',
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=0,
        offset=None,
        scale=None,
        spatial_resolution=1.0,
        center_wavelength=None,
        full_width_half_max=None,
    )
)

register_static_metadata(provider, collection, metadata)
