"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         ecmwf-forecast
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'ecmwf-forecast'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='data',
            longname='GRIB2 data file',
            description='The forecast data, as a grib2 file. Subsets of the data can be loaded using information from '
            'the associated index file.',
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        )
    ]
)

register_static_metadata(provider, collection, metadata)
