"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         hrea
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'hrea'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='lightscore',
            longname='Probability of electrification',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='light-composite',
            longname='Nighttime light annual composite',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='night-proportion',
            longname='Proportion of nights a settlement is brighter than uninhabited areas',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='estimated-brightness',
            longname='Estimated brightness levels',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
    ]
)

register_static_metadata(provider, collection, metadata)
