"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         hgb
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'hgb'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='aboveground',
            longname='Global above-ground biomass',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='belowground',
            longname='Global below-ground biomass',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='aboveground_uncertainty',
            longname='Uncertainty associated with global above-ground biomass',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='belowground_uncertainty',
            longname='Uncertainty associated with global below-ground biomass',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
    ]
)

register_static_metadata(provider, collection, metadata)
