"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         io-biodiversity
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'io-biodiversity'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='data',
            longname='Biodiversity Intactness',
            description='Terrestrial biodiversity intactness at 100m resolution',
            unit=None,
            roles=['data'],
            dtype='float32',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=100.0,
            center_wavelength=None,
            full_width_half_max=None,
        )
    ]
)

register_static_metadata(provider, collection, metadata)
