"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         landsat-c2-l1
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'landsat-c2-l1'

metadata = CollectionMetadata(
    Variable(
        name='red',
        longname='red',
        description='Visible red',
        unit='watt/steradian/square_meter/micrometer',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=0,
        offset=None,
        scale=None,
        spatial_resolution=60.0,
        center_wavelength=0.65,
        full_width_half_max=0.1,
    ),
    Variable(
        name='green',
        longname='green',
        description='Visible green',
        unit='watt/steradian/square_meter/micrometer',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=0,
        offset=None,
        scale=None,
        spatial_resolution=60.0,
        center_wavelength=0.55,
        full_width_half_max=0.1,
    ),
    Variable(
        name='nir08',
        longname='nir08',
        description='Near infrared',
        unit='watt/steradian/square_meter/micrometer',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=0,
        offset=None,
        scale=None,
        spatial_resolution=60.0,
        center_wavelength=0.75,
        full_width_half_max=0.1,
    ),
    Variable(
        name='nir09',
        longname='nir09',
        description='Near infrared',
        unit='watt/steradian/square_meter/micrometer',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=0,
        offset=None,
        scale=None,
        spatial_resolution=60.0,
        center_wavelength=0.95,
        full_width_half_max=0.3,
    ),
)

register_static_metadata(provider, collection, metadata)
