"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         modis-16A3GF-061
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'modis-16A3GF-061'

metadata = CollectionMetadata(
    Variable(
        name='hdf',
        longname='Source data containing all bands',
        description=None,
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='ET_500m',
        longname='Total of Evapotranspiration',
        description=None,
        unit='kg/m^2/year',
        roles=['data'],
        dtype='uint16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=0.1,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='LE_500m',
        longname='Average of Latent Heat Flux',
        description=None,
        unit='J/m^2/day',
        roles=['data'],
        dtype='int16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=10000,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='PET_500m',
        longname='Total Potential Evapotranspiration',
        description=None,
        unit='kg/m^2/year',
        roles=['data'],
        dtype='uint16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=0.1,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='PLE_500m',
        longname='Average of Potential Latent Heat Flux',
        description=None,
        unit='J/m^2/day',
        roles=['data'],
        dtype='int16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=10000,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='ET_QC_500m',
        longname='Evapotranspiration Quality Assessment',
        description=None,
        unit='Percent',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
