"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         modis-17A3HGF-061
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'modis-17A3HGF-061'

metadata = CollectionMetadata(
    Variable(
        name='hdf',
        longname='Source data containing all bands',
        description=None,
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='Gpp_500m',
        longname='Gross Primary Productivity',
        description=None,
        unit='kg C/m^2',
        roles=['data'],
        dtype='uint16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=0.0001,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='Npp_500m',
        longname='Net Primary Productivity',
        description=None,
        unit='kg C/m^2',
        roles=['data'],
        dtype='int16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=0.0001,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='Npp_QC_500m',
        longname='Quality control',
        description=None,
        unit='Percent',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
