"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         modis-09Q1-061
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'modis-09Q1-061'

metadata = CollectionMetadata(
    Variable(
        name='hdf',
        longname='Source data containing all bands',
        description=None,
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='sur_refl_b01',
        longname='red',
        description=None,
        unit=None,
        roles=['data', 'reflectance'],
        dtype='int16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=0.0001,
        spatial_resolution=250.0,
        center_wavelength=0.645,
        full_width_half_max=0.5,
    ),
    Variable(
        name='sur_refl_b02',
        longname='nir08',
        description=None,
        unit=None,
        roles=['data', 'reflectance'],
        dtype='int16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=0.0001,
        spatial_resolution=250.0,
        center_wavelength=0.8585,
        full_width_half_max=0.35,
    ),
    Variable(
        name='sur_refl_qc_250m',
        longname='Surface Reflectance 250m Band Quality Control flags',
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=250.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='sur_refl_state_250m',
        longname='Surface Reflectance 250m State flags',
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=250.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
