"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         modis-10A1-061
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'modis-10A1-061'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='hdf',
            longname='Source data containing all bands',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='NDSI',
            longname='Raw NDSI values (i.e. prior to screening).',
            description=None,
            unit=None,
            roles=['data'],
            dtype='int16',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=0.0001,
            spatial_resolution=500.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='orbit_pnt',
            longname='Pointer to the orbit of the swath mapped into each grid cell.',
            description=None,
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=500.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='granule_pnt',
            longname='Pointer for identifying the swath mapped into each grid cell.',
            description=None,
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=500.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='NDSI_Snow_Cover',
            longname='Gridded NDSI snow cover and data flag values.',
            description=None,
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=500.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='Snow_Albedo_Daily_Tile',
            longname='Daily snow albedo corresponding to the NDSI_Snow_Cover parameter.',
            description=None,
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=500.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='NDSI_Snow_Cover_Basic_QA',
            longname='A general estimate of the quality of the algorithm result.',
            description=None,
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=500.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='NDSI_Snow_Cover_Algorithm_Flags_QA',
            longname='Algorithm-specific bit flags set for data screens and for inland water.',
            description=None,
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=500.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
    ]
)

register_static_metadata(provider, collection, metadata)
