"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         modis-15A2H-061
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'modis-15A2H-061'

metadata = CollectionMetadata(
    Variable(
        name='hdf',
        longname='Source data containing all bands',
        description=None,
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='Lai_500m',
        longname='Leaf Area Index',
        description='The one-sided green leaf area per unit ground area in broadleaf canopies and as one-half the '
        'total needle surface area per unit ground area in coniferous canopies',
        unit='m^2/m^2',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=0.1,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='Fpar_500m',
        longname='Fraction of Photosynthetically Active Radiation',
        description='The fraction of incident photosynthetically active radiation (400-700 nm) absorbed by the green '
        'elements of a vegetation canopy.',
        unit='Percent',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=0.01,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='FparLai_QC',
        longname='Quality for FPAR and LAI',
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='FparExtra_QC',
        longname='Extra detail Quality for FPAR and LAI',
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='LaiStdDev_500m',
        longname='Standard deviation of LAI',
        description=None,
        unit='m^2/m^2',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=0.1,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='FparStdDev_500m',
        longname='Standard deviation of FPAR',
        description=None,
        unit='Percent',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=0.01,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
