"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         modis-64A1-061
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'modis-64A1-061'

metadata = CollectionMetadata(
    Variable(
        name='QA',
        longname='Quality Assurance Indicators',
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='hdf',
        longname='Source data containing all bands',
        description=None,
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='Last_Day',
        longname='Last day of the year of reliable change detection',
        description=None,
        unit='Day',
        roles=['data'],
        dtype='int16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='Burn_Date',
        longname='Burn day of year',
        description=None,
        unit='Day',
        roles=['data'],
        dtype='int16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='First_Day',
        longname='First day of the year of reliable change detection',
        description=None,
        unit='Day',
        roles=['data'],
        dtype='int16',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='Burn_Date_Uncertainty',
        longname='Estimated uncertainty in burn day',
        description=None,
        unit='Day',
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
