"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         modis-10A2-061
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'modis-10A2-061'

metadata = CollectionMetadata(
    Variable(
        name='hdf',
        longname='Source data containing all bands',
        description=None,
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='Maximum_Snow_Extent',
        longname='Maximum snow extent over the 8-day period.',
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='Eight_Day_Snow_Cover',
        longname='Snow chronology bit flags for each day in the eight-day observation period.',
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=500.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
