"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         modis-14A1-061
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'modis-14A1-061'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='QA',
            longname='Pixel quality indicators',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='hdf',
            longname='Source data containing all bands',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='MaxFRP',
            longname='Maximum Fire Radiative Power',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='sample',
            longname='Position of fire pixel within scan',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='FireMask',
            longname='Confidence of fire',
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
    ]
)

register_static_metadata(provider, collection, metadata)
