"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         noaa-mrms-qpe-1h-pass1
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'noaa-mrms-qpe-1h-pass1'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='cog',
            longname='Processed Cloud Optimized GeoTIFF file',
            description=None,
            unit='mm',
            roles=['data'],
            dtype='float64',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=1000.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='grib2',
            longname='Original GRIB2 file',
            description=None,
            unit='mm',
            roles=['data'],
            dtype='float64',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=1000.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
    ]
)

register_static_metadata(provider, collection, metadata)
