"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         noaa-cdr-ocean-heat-content
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'noaa-cdr-ocean-heat-content'

metadata = CollectionMetadata(
    Variable(
        name='heat_content',
        longname='Ocean Heat Content anomalies from WOA09',
        description=None,
        unit='10^18 joules',
        roles=['data'],
        dtype='float32',
        preferred_resampling=None,
        nodata_value=float('nan'),
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='mean_salinity',
        longname='Mean salinity anomalies from WOA09',
        description=None,
        unit=None,
        roles=['data'],
        dtype='float32',
        preferred_resampling=None,
        nodata_value=float('nan'),
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='mean_temperature',
        longname='Mean temperature anomalies from WOA09',
        description=None,
        unit='degrees Celsius',
        roles=['data'],
        dtype='float32',
        preferred_resampling=None,
        nodata_value=float('nan'),
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='mean_halosteric_sea_level',
        longname='Mean halosteric sea level anomalies from WOA09',
        description=None,
        unit='millimeters',
        roles=['data'],
        dtype='float32',
        preferred_resampling=None,
        nodata_value=float('nan'),
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='mean_thermosteric_sea_level',
        longname='Mean thermosteric sea level anomalies from WOA09',
        description=None,
        unit='millimeters',
        roles=['data'],
        dtype='float32',
        preferred_resampling=None,
        nodata_value=float('nan'),
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='mean_total_steric_sea_level',
        longname='Mean total steric sea level anomalies from WOA09',
        description=None,
        unit='millimeters',
        roles=['data'],
        dtype='float32',
        preferred_resampling=None,
        nodata_value=float('nan'),
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
