"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         noaa-nclimgrid-monthly
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'noaa-nclimgrid-monthly'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='prcp',
            longname='Monthly Precipitation (mm)',
            description=None,
            unit='mm',
            roles=['data'],
            dtype='float32',
            preferred_resampling=None,
            nodata_value=float('nan'),
            offset=None,
            scale=None,
            spatial_resolution=5000.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='tavg',
            longname='Monthly Average Temperature (degree Celsius)',
            description=None,
            unit='degree Celsius',
            roles=['data'],
            dtype='float32',
            preferred_resampling=None,
            nodata_value=float('nan'),
            offset=None,
            scale=None,
            spatial_resolution=5000.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='tmax',
            longname='Monthly Maximmum Temperature (degree Celsius)',
            description=None,
            unit='degree Celsius',
            roles=['data'],
            dtype='float32',
            preferred_resampling=None,
            nodata_value=float('nan'),
            offset=None,
            scale=None,
            spatial_resolution=5000.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='tmin',
            longname='Monthly Minimum Temperature (degree Celsius)',
            description=None,
            unit='degree Celsius',
            roles=['data'],
            dtype='float32',
            preferred_resampling=None,
            nodata_value=float('nan'),
            offset=None,
            scale=None,
            spatial_resolution=5000.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
    ]
)

register_static_metadata(provider, collection, metadata)
