"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         nasa-nex-gddp-cmip6
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'nasa-nex-gddp-cmip6'

metadata = CollectionMetadata(
    Variable(
        name='pr',
        longname='Precipitation',
        description='Precipitation',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='tas',
        longname='Daily Near-Surface Air Temperature',
        description='Daily Near-Surface Air Temperature',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='hurs',
        longname='Near-Surface Relative Humidity',
        description='Near-Surface Relative Humidity',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='huss',
        longname='Near-Surface Specific Humidity',
        description='Near-Surface Specific Humidity',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='rlds',
        longname='Surface Downwelling Longwave Radiation',
        description='Surface Downwelling Longwave Radiation',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='rsds',
        longname='Surface Downwelling Shortwave Radiation',
        description='Surface Downwelling Shortwave Radiation',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='tasmax',
        longname='Daily Maximum Near-Surface Air Temperature',
        description='Daily Maximum Near-Surface Air Temperature',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='tasmin',
        longname='Daily Minimum Near-Surface Air Temperature',
        description='Daily Minimum Near-Surface Air Temperature',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='sfcWind',
        longname='Daily-Mean Near-Surface Wind Speed',
        description='Daily-Mean Near-Surface Wind Speed',
        unit=None,
        roles=['data'],
        dtype=None,
        preferred_resampling=None,
        nodata_value=None,
        offset=None,
        scale=None,
        spatial_resolution=None,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
