"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         noaa-cdr-sea-surface-temperature-whoi
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'noaa-cdr-sea-surface-temperature-whoi'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='fill_missing_qc',
            longname=None,
            description=None,
            unit=None,
            roles=['data'],
            dtype='float32',
            preferred_resampling=None,
            nodata_value=float('nan'),
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='sea_surface_temperature',
            longname=None,
            description=None,
            unit='degree Celsius',
            roles=['data'],
            dtype='float32',
            preferred_resampling=None,
            nodata_value=float('nan'),
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
    ]
)

register_static_metadata(provider, collection, metadata)
