"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         noaa-cdr-sea-surface-temperature-optimum-interpolation
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'noaa-cdr-sea-surface-temperature-optimum-interpolation'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='err',
            longname=None,
            description=None,
            unit='Celsius',
            roles=['data'],
            dtype='int16',
            preferred_resampling=None,
            nodata_value=-999,
            offset=None,
            scale=0.009999999776482582,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='ice',
            longname=None,
            description=None,
            unit='%',
            roles=['data'],
            dtype='int16',
            preferred_resampling=None,
            nodata_value=-999,
            offset=None,
            scale=0.009999999776482582,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='sst',
            longname=None,
            description=None,
            unit='Celsius',
            roles=['data'],
            dtype='int16',
            preferred_resampling=None,
            nodata_value=-999,
            offset=None,
            scale=0.009999999776482582,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='anom',
            longname=None,
            description=None,
            unit='Celsius',
            roles=['data'],
            dtype='int16',
            preferred_resampling=None,
            nodata_value=-999,
            offset=None,
            scale=0.009999999776482582,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='netcdf',
            longname=None,
            description=None,
            unit=None,
            roles=['data'],
            dtype=None,
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=None,
            center_wavelength=None,
            full_width_half_max=None,
        ),
    ]
)

register_static_metadata(provider, collection, metadata)
