"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         sentinel-1-rtc
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'sentinel-1-rtc'

metadata = CollectionMetadata(
    Variable(
        name='hh',
        longname='HH: horizontal transmit, horizontal receive',
        description='Terrain-corrected gamma naught values of signal transmitted with horizontal polarization and '
        'received with horizontal polarization with radiometric terrain correction applied.',
        unit=None,
        roles=['data'],
        dtype='float32',
        preferred_resampling=None,
        nodata_value=-32768,
        offset=None,
        scale=None,
        spatial_resolution=10.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='hv',
        longname='HV: horizontal transmit, vertical receive',
        description='Terrain-corrected gamma naught values of signal transmitted with horizontal polarization and '
        'received with vertical polarization with radiometric terrain correction applied.',
        unit=None,
        roles=['data'],
        dtype='float32',
        preferred_resampling=None,
        nodata_value=-32768,
        offset=None,
        scale=None,
        spatial_resolution=10.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='vh',
        longname='VH: vertical transmit, horizontal receive',
        description='Terrain-corrected gamma naught values of signal transmitted with vertical polarization and '
        'received with horizontal polarization with radiometric terrain correction applied.',
        unit=None,
        roles=['data'],
        dtype='float32',
        preferred_resampling=None,
        nodata_value=-32768,
        offset=None,
        scale=None,
        spatial_resolution=10.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='vv',
        longname='VV: vertical transmit, vertical receive',
        description='Terrain-corrected gamma naught values of signal transmitted with vertical polarization and '
        'received with vertical polarization with radiometric terrain correction applied.',
        unit=None,
        roles=['data'],
        dtype='float32',
        preferred_resampling=None,
        nodata_value=-32768,
        offset=None,
        scale=None,
        spatial_resolution=10.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
