"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         usgs-lcmap-conus-v13
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'usgs-lcmap-conus-v13'

metadata = CollectionMetadata(
    variables=[
        Variable(
            name='lcpri',
            longname='Primary Land Cover',
            description='Land cover classification consisting of eight general land cover types. The most likely land '
            'cover according to the modeling process.',
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=0,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='lcsec',
            longname='Secondary Land Cover',
            description='Land cover classification consisting of eight general land cover types. The second most likely '
            'land cover according to the modeling process.',
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=0,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='scmag',
            longname='Change Magnitude',
            description="The spectral strength or intensity of a time series model 'break' when spectral observations "
            'have diverged from the model predictions.',
            unit=None,
            roles=['data'],
            dtype='float32',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='scmqa',
            longname='Model Quality',
            description='Information regarding the type of time series model applied to the current product year.',
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='browse',
            longname='USGS Browse Image',
            description='Image generated by USGS for viewing LCMAP classification data in web applications.',
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=0,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='lcachg',
            longname='Annual Land Cover Change',
            description='Synthesis of Primary Land Cover of current and previous year identifying changes in land cover '
            'class.',
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=0,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='sclast',
            longname='Time Since Last Change',
            description='Time, in days, since the last identified Spectral Change (SCTIME).',
            unit=None,
            roles=['data'],
            dtype='uint16',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='scstab',
            longname='Spectral Stability Period',
            description='Measure of the amount of time in days that a pixel has been in its current spectral state as of '
            'July 1st. Current spectral state can refer to both during stable time series segments or a '
            'period outside of stable time series segments.',
            unit=None,
            roles=['data'],
            dtype='uint16',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='sctime',
            longname='Time of Spectral Change',
            description='Represents the timing of a spectral change within the current product year as the day of year '
            'the change occurred.',
            unit=None,
            roles=['data'],
            dtype='uint16',
            preferred_resampling=None,
            nodata_value=None,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='lcpconf',
            longname='Primary Land Cover Confidence',
            description='Provides provenance tracking and a measure of confidence that the Primary Land Cover label '
            'matches the training data.',
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=0,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
        Variable(
            name='lcsconf',
            longname='Secondary Land Cover Confidence',
            description='Provides provenance tracking and a measure of confidence that the Secondary Land Cover label '
            'matches the training data.',
            unit=None,
            roles=['data'],
            dtype='uint8',
            preferred_resampling=None,
            nodata_value=0,
            offset=None,
            scale=None,
            spatial_resolution=30.0,
            center_wavelength=None,
            full_width_half_max=None,
        ),
    ]
)

register_static_metadata(provider, collection, metadata)
