"""
This file has been automatically generated by prefetch_metadata.py

 * Creation Date:      2025-07-08
 * Provider:           planetary_computer
 * Collection:         usda-cdl
 * Manually modified:  No
"""

from datetime import date

from stacathome.metadata import CollectionMetadata, register_static_metadata, Variable

__all__ = [
    'creation_date',
    'provider',
    'collection',
    'metadata',
]

creation_date = date.fromisoformat('2025-07-08')
provider = 'planetary_computer'
collection = 'usda-cdl'

metadata = CollectionMetadata(
    Variable(
        name='corn',
        longname=None,
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=255,
        offset=None,
        scale=None,
        spatial_resolution=30.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='wheat',
        longname=None,
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=255,
        offset=None,
        scale=None,
        spatial_resolution=30.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='cotton',
        longname=None,
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=255,
        offset=None,
        scale=None,
        spatial_resolution=30.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='cropland',
        longname=None,
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=0,
        offset=None,
        scale=None,
        spatial_resolution=30.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='soybeans',
        longname=None,
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=255,
        offset=None,
        scale=None,
        spatial_resolution=30.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='confidence',
        longname=None,
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=0,
        offset=None,
        scale=None,
        spatial_resolution=30.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
    Variable(
        name='cultivated',
        longname=None,
        description=None,
        unit=None,
        roles=['data'],
        dtype='uint8',
        preferred_resampling=None,
        nodata_value=0,
        offset=None,
        scale=None,
        spatial_resolution=30.0,
        center_wavelength=None,
        full_width_half_max=None,
    ),
)

register_static_metadata(provider, collection, metadata)
